version: '3.7'

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercedes
      MYSQL_USER: mercedes
      MYSQL_PASSWORD: mercedes
    ports:
      - "8306:3306"
    networks:
      - mercedes
      
  flyway:
    container_name: flyway
    image: flyway/flyway:latest
    command: migrate
    
    environment:
      FLYWAY_URL: jdbc:mysql://db
      FLYWAY_SCHEMAS: mercedes
      FLYWAY_USER: mercedes
      FLYWAY_PASSWORD: mercedes
      
      FLYWAY_CONNECT_RETRIES: 60
    volumes:
      - ./src/test/resources/flyway/migrations:/flyway/sql
      - ./src/test/resources/flyway/conf:/flyway/conf
    depends_on:
    - db
    networks:
    - mercedes
    
networks:
  mercedes:
    driver: bridge
    name: mercedes-to-mercedes